#!/usr/bin/env bash

# example: VERSION=1.0 ./build_image

SOFTWARE=habitus

rm -f Dockefile
cp Dockerfile.template Dockerfile
sed -i "s/<VER>/$VERSION/g" Dockerfile


/usr/local/bin/docker build -t $SOFTWARE:$VERSION  --force-rm .
